db-uri = "postgres://chill99:1234@db:5432/chill99db"
db-schema = "public"
db-anon-role = "web_anon"
# The JWT secret can be provided via environment variable PGRST_JWT_SECRET
# jwt-secret = "<replace-with-your-jwt-secret>"
server-port = 3000
